### ISSUE TITLE
Interpretation of Mutation Score Results

### ISSUE THREAD

**Issue by Moo-cow** [tyang816/ProtSSN#7]
Hi ,
I hope this message finds you well. I have been reading your research work and have some questions regarding the results obtained from your protein mutation prediction model, particularly concerning the interpretation of mutation scores.

`--------------- ProtSSN k20_h512 ---------------                                                                                                                          
>>> Protein names: ['A0A1I9GEU1_NEIME_Kennouche_2019', 'A0A2Z5U3Z0_9INFA_Doud_2016']                                                                                      
>>> Number of proteins: 2                                                                                                                                                 
>>> k20_h512 Number of trainable parameter: 148.10M                                                                                                                       
>>> A0A1I9GEU1_NEIME_Kennouche_2019: 0.034114723952631244; mutant_num: 922                                                                                                
>>> A0A2Z5U3Z0_9INFA_Doud_2016: 0.5228872937740011; mutant_num: 10715                                                                                                     
>>> ProtSSN_k20_h512 average spearmanr: 0.2785010088633162   `

I got two files : A0A2Z5U3Z0_9INFA_Doud_2016.csv and A0A1I9GEU1_NEIME_Kennouche_2019.csv 

What does each column mean, and how do you screen for highly active mutations ？

`<html xmlns:v="urn:schemas-microsoft-com:vml" xmlns:o="urn:schemas-microsoft-com:office:office" xmlns:x="urn:schemas-microsoft-com:office:excel" xmlns="http://www.w3.org/TR/REC-html40">
<head>

<meta name=Generator content="Microsoft Excel">

<style>

</style>
</head>
<body>

mutant | score | ProtSSN_k10_h512
-- | -- | --
F1I | -3.598 | -9.413104057
F1L | -0.678 | -12.16771984
F1Y | -2.373 | -12.62869453
F1V | 1.299 | -9.644733429
F1S | -0.127 | -12.13227844
T2A | 0.786 | -15.00946903
T2N | 1.111 | -9.123391151
T2P | -0.107 | -15.6654501
T2S | 0.217 | -6.05307436
T2I | 1.149 | -20.49755859
L3F | -1.086 | -11.90341187
L3H | 1.336 | -15.95216751
L3I | 1.394 | -7.772084236
L3P | 1.063 | -12.33663845
L3R | -8.297 | -12.84322739
L3V | -2.661 | -9.14486599
I4F | -1.145 | -13.00201607
I4M | -2.834 | -8.143092155
I4N | 3.554 | -11.65526295
I4L | 2.118 | -7.117062092
I4T | -0.215 | -9.421805382
I4V | 1.646 | -7.484519482
E5V | -1.269 | -12.28852558
E5Q | 0.315 | -5.395954609
E5K | -1.164 | -8.709512711
E5D | 0.486 | -7.592521191
E5G | 0.104 | -11.92467213

</body>

</html>
`
Thank you for taking the time to read my email, and I look forward to your response.

Best regards,

**Comment by tyang816** [comment]
The column `score` indicates the experimental data obtained by high-throughput DMS. Please note that this is obtained from real experiments. If you are a new protein, I default this column to 0. The column `ProtSSN_k10_h512` indicates the scores of these mutations by the `k10_h512` model. The higher the score, the more beneficial the point mutation is.

If you want to use it for directed evolution wet experiments, first:

1. It is recommended to use high-precision structures, AF3 or even crystal structures.

2. Select the `ensemble` model and sort the predicted scores from high to low. Select mutations with high scores. We do not recommend that you use multiple point mutations in the first round.

Thank you for following our work. By the way, our model has been run through multiple wet experiments and achieved good results.

**Comment by Moo-cow** [comment]
`The higher the score, the more beneficial the point mutation is.`  Does the score comparison of the ProtSSN_ensemble model take negative signs into account?

**Comment by tyang816** [comment]
The negative sign is taken into account, not the absolute value. -1 > -2.

**Comment by Moo-cow** [comment]
Thank you for your patient answers, looking forward to a good result.

**Comment by tyang816** [comment]
Please also consider some prior knowledge, such as conserved sites or beneficial mutations made by other homologous proteins, rational design, etc. I wish you a successful experiment.

**Comment by Moo-cow** [comment]
Thank you, I will consider it. Based on your previous experience, how many of the top-ranked mutation sites located in active pockets would you suggest selecting? Do you have any recommendations?

**Comment by tyang816** [comment]
Usually, the top 30 are selected, but not all of them are experimented on. Only 10-20 are selected from the 30 predicted by the model based on prior knowledge, plus some rationally designed ones.

**Comment by Moo-cow** [comment]
Thank you very much for your suggestion. 
Best wishes.
：）
